-- MySQL Script generated by MySQL Workbench
-- Wed Oct  7 20:36:04 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PALHACO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PALHACO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `personalidade` VARCHAR(45) NOT NULL,
  `nota` DOUBLE NOT NULL,
  `cache` DOUBLE NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`INSTRUMENTO_DE_RISADA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INSTRUMENTO_DE_RISADA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(300) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `PALHACO_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_INSTRUMENTO_DE_RISADA_PALHACO_idx` (`PALHACO_id` ASC) VISIBLE,
  CONSTRAINT `fk_INSTRUMENTO_DE_RISADA_PALHACO`
    FOREIGN KEY (`PALHACO_id`)
    REFERENCES `mydb`.`PALHACO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
